#ifndef QWT3D_BAR_P_H
#define QWT3D_BAR_P_H

#include "qwt3d_bar.h"
#include "qwt3d_types.h"
#include "qwt3d_color.h"

#include <QOpenGLBuffer>
#include <QOpenGLVertexArrayObject>
#include <QOpenGLShaderProgram>
#include <QVector3D>
#include <QVector4D>

#include <vector>
#include <cfloat>

/**
 * @brief Vertex structure for VBO upload
 * @details Each vertex has position (3 floats), normal (3 floats), and color (4 floats).
 *          Total stride = 40 bytes, matching the surface shader attribute layout:
 *          location 0 = position, location 1 = normal, location 2 = color.
 */
struct BarVertex
{
    QVector3D position;
    QVector3D normal;
    QVector4D color;
};

/**
 * @brief Specification of a single bar (axis-aligned cuboid)
 * @details Generated by the setSamples() entry points and consumed by buildVBO()
 *          to emit the 6-face box geometry. center marks the bar footprint center
 *          on the xy-plane; baseZ/topZ span the bar along the z-axis (baseZ <= topZ).
 */
struct Qwt3DBarSpec
{
    Triple center;
    double halfWidth;
    double halfDepth;
    double baseZ;
    double topZ;
    double height;  ///< original z value, used to recompute baseZ/topZ when baseline changes
};

class Qwt3DBar::PrivateData
{
    QWT_DECLARE_PUBLIC(Qwt3DBar)

public:
    explicit PrivateData(Qwt3DBar* q);
    ~PrivateData();

    // Bar specifications (filled by setSamples)
    std::vector<Qwt3DBarSpec> m_bars;

    // Bar geometry
    double m_barWidth;   // <= 0 means auto (80% of spacing)
    double m_barDepth;   // <= 0 means auto
    double m_baseline;
    double m_spacingX;  ///< cached grid spacing for auto-width recompute
    double m_spacingY;  ///< cached grid spacing for auto-depth recompute

    // Plot style and color
    Qwt3DBar::BarStyle m_barStyle;
    Qwt3DColor* m_dataColor;
    RGBA m_meshColor;
    double m_meshLineWidth;
    double m_polygonOffset;

    // GL resources (created lazily in draw())
    bool m_vboDirty;
    bool m_shaderInitialized;
    QOpenGLBuffer m_vertexBuffer;
    QOpenGLBuffer m_indexBuffer;
    QOpenGLVertexArrayObject m_vao;
    QOpenGLShaderProgram m_shader;

    // Index counts (tri indices first, then line indices in the same EBO)
    int m_triIndexCount;
    int m_lineIndexCount;
    int m_vertexCount;

    // Cached hull
    ParallelEpiped m_hull;

    // 2D grid metadata (set by setSamples(double**, ...) and setSamples(const Qwt3DFunctionData&))
    bool m_isGridData = false;
    int m_gridColumns = 0;
    int m_gridRows = 0;
    double m_gridMinX = 0.0;
    double m_gridMaxX = 0.0;
    double m_gridMinY = 0.0;
    double m_gridMaxY = 0.0;
    std::vector<std::vector<double>> m_gridZ;  ///< 原始 z 矩阵的拷贝，避免依赖 m_bars 排列顺序
};

inline Qwt3DBar::PrivateData::PrivateData(Qwt3DBar* q)
    : q_ptr(q)
    , m_barWidth(0.0)
    , m_barDepth(0.0)
    , m_baseline(0.0)
    , m_spacingX(0.0)
    , m_spacingY(0.0)
    , m_barStyle(Qwt3DBar::FilledMesh)
    , m_dataColor(nullptr)
    , m_meshColor(RGBA(0.0, 0.0, 0.0, 1.0))
    , m_meshLineWidth(1.0)
    , m_polygonOffset(0.5)
    , m_vboDirty(true)
    , m_shaderInitialized(false)
    , m_triIndexCount(0)
    , m_lineIndexCount(0)
    , m_vertexCount(0)
    , m_hull(Triple(0, 0, 0), Triple(0, 0, 0))
{
    // QOpenGLBuffer with IndexBuffer target
    m_indexBuffer = QOpenGLBuffer(QOpenGLBuffer::IndexBuffer);
}

inline Qwt3DBar::PrivateData::~PrivateData()
{
    // Destroy GL resources (safe to call even without current context)
    m_vertexBuffer.destroy();
    m_indexBuffer.destroy();
    m_vao.destroy();

    // Clean up color functor
    if (m_dataColor)
        m_dataColor->destroy();
}

#endif // QWT3D_BAR_P_H
